export const FETCH_ALL_BOOKS_SUCCESS = 'FETCH_ALL_BOOKS_SUCCESS';
export const FETCH_ALL_BOOKS_FAILED = 'FETCH_ALL_BOOKS_FAILED';

export const ASSOCIATE_RENTAL_WITH_BOOK = 'ASSOCIATE_RENTAL_WITH_BOOK';
