export const FETCH_ALL_BOOKS_SUCCESS = 'FETCH_ALL_BOOKS_SUCCESS';
export const FETCH_ALL_BOOKS_FAILED = 'FETCH_ALL_BOOKS_FAILED';

export const UPDATE_BOOK_SUCCESS = 'UPDATE_BOOK_SUCCESS';

export const ADD_NEW_BOOK_SUCCESS = 'ADD_NEW_BOOK_SUCCESS';
export const ADD_NEW_BOOK_FAILED = 'ADD_NEW_BOOK_FAILED';

export const EXPAND_BOOK_INFO = 'EXPAND_BOOK_INFO';
